# Generated by Django 5.0.6 on 2025-08-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_category_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
    ]
