# Generated by Django 5.0.14 on 2025-09-16 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_remove_menuitem_restaurant"),
        ("userprofile", "0002_userprofile_bio_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
            },
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="being_delivered",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="received",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="city",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="country",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="cuisine",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="is_active",
        ),
        migrations.AddField(
            model_name="orders",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("TAKING", "Order Taking"),
                    ("PREPARING", "Preparing"),
                    ("SERVING", "Serving"),
                    ("COMPLETED", "Completed"),
                ],
                default="TAKING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("DINE_IN", "Dine In"),
                    ("TAKEAWAY", "Takeaway"),
                    ("DELIVERY", "Delivery"),
                ],
                default="DINE_IN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waiter_orders",
                to="userprofile.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="restaurants.menu",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="billing_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="billing_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="billing_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="userprofile.userprofile",
            ),
        ),
        migrations.AlterModelTable(
            name="orders",
            table=None,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="restaurants.category",
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("table_number", models.PositiveIntegerField()),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tables",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("restaurant", "table_number")},
            },
        ),
        migrations.AddField(
            model_name="orders",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="restaurants.table",
            ),
        ),
    ]
