# Generated by Django 5.0.14 on 2025-09-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_category_alter_orders_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemingredient",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="restaurants.menuitem",
            ),
        ),
    ]
