# Generated by Django 5.0.14 on 2025-09-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_menuitemingredient_menu_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemingredient",
            name="menu_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="restaurants.menuitem",
            ),
            preserve_default=False,
        ),
    ]
