# Generated by Django 5.0.14 on 2025-09-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_menuitemingredient_menu_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="restaurant",
        ),
    ]
