# Generated by Django 5.0.14 on 2025-09-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_remove_cart_restaurant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "menu_item")},
        ),
    ]
