# Generated by Django 5.0.14 on 2025-09-25 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "restaurant_owner"},
                related_name="owned_restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
