
SECRET_KEY=qwqwqwqwqwqwqjsqhsqgjsgqsjqjgsqjgswqjgswgjqgj

COMPANY_NAME=resturant
COMPANY_COPYRIGHT=resturant
COMPANY_ADDRESS=resturant
COMPANY_PHONE=1234567890
COMPANY_EMAIL=info.com
COMPANY_WEBSITE=resr.com
COMPANY_LOGO=test
COMPANY_FAVICON=test
COMPANY_LOGO_TEXT=PureLogics
COMPANY_LOGO_MINI=PL
COMPANY_STARTING_YEAR=2002

PRIMARY_COLOR=#000000
SECONDARY_COLOR=#000000
BUTTON_COLOR=#000000
TEXT_COLOR=#000000

REACT_DOMAIN=http://localhost:3000
DOMAIN=purelogics.net

EMAIL_FROM=mohsin.raza@purelogics.net
EMAIL_HOST_USER=mohsin.raza@purelogics.net
EMAIL_HOST_PASSWORD=ksqeomsesfrjbexm
EMAIL_HOST=smtp.gmail.com