# Generated by Django 5.0.14 on 2025-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_useractivation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("restaurant_owner", "Restaurant Owner"),
                    ("waiter", "Waiter"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="user",
                max_length=255,
            ),
        ),
    ]
