# Generated by Django 5.0.14 on 2025-09-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_user_type"),
        ("restaurants", "0011_restaurant_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiters",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("waiter", "Waiter"),
                    ("restaurant_owner", "Restaurant Owner"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="user",
                max_length=255,
            ),
        ),
    ]
