# Generated by Django 5.0.14 on 2025-09-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_restaurant_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="restaurant",
        ),
    ]
