# Generated by Django 5.0.14 on 2025-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_userprofile_bio_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("waiter", "Waiter"),
                    ("restaurant_owner", "Restaurant Owner"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="customer",
                max_length=50,
            ),
        ),
    ]
