# Generated by Django 5.0.14 on 2025-09-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
    ]
